import * as path from 'node:path'
import { Anomaly } from './types'

const SEVERITY_ORDER: Record<Anomaly['severity'], number> = { critical: 0, major: 1, minor: 2 }
const SEVERITY_EMOJI: Record<Anomaly['severity'], string> = { critical: '🔴', major: '🟠', minor: '⚪' }

export function buildMarkdownReport(input: {
  runId: string
  startUrl: string
  pagesVisited: string[]
  actionsPerformed: number
  anomalies: Anomaly[]
  domain?: string
  qualityGate?: {
    decision: string
    criticalCount: number
    majorCount: number
    minorCount: number
    recommendation: string
    blockingReasons: string[]
  }
  defects?: Array<{
    id: string
    title: string
    severity: Anomaly['severity']
    triageStatus: string
  }>
  auditTrail?: Array<{ phase: string; agent: string; action: string; reason: string }>
}): string {
  const { runId, startUrl, pagesVisited, actionsPerformed, anomalies } = input
  const critical = anomalies.filter((a) => a.severity === 'critical')
  const major = anomalies.filter((a) => a.severity === 'major')
  const minor = anomalies.filter((a) => a.severity === 'minor')

  const sorted = [...anomalies].sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity])

  const lines: string[] = [
    `# Exploration report — ${runId}`,
    '',
    `**Start URL:** ${startUrl}`,
    ...(input.domain ? [`**Domain:** ${input.domain}`] : []),
    `**Pages visited:** ${pagesVisited.length}`,
    `**Actions performed:** ${actionsPerformed}`,
    `**Anomalies found:** ${anomalies.length} (${critical.length} critical, ${major.length} major, ${minor.length} minor)`,
    ...(input.qualityGate
      ? [
          `**Quality gate:** ${input.qualityGate.decision}`,
          `**Recommendation:** ${input.qualityGate.recommendation}`,
        ]
      : []),
    '',
    '## Summary',
    '',
    anomalies.length === 0
      ? 'No anomalies detected during this exploration run.'
      : `| Severity | Count |\n| --- | --- |\n| 🔴 Critical | ${critical.length} |\n| 🟠 Major | ${major.length} |\n| ⚪ Minor | ${minor.length} |`,
    '',
  ]

  if (input.qualityGate?.blockingReasons.length) {
    lines.push('## Blocking reasons', '', ...input.qualityGate.blockingReasons.map((r) => `- ${r}`), '')
  }

  if (input.defects && input.defects.length > 0) {
    lines.push(
      '## Triaged defects',
      '',
      '| ID | Severity | Status | Title |',
      '| --- | --- | --- | --- |',
      ...input.defects.map(
        (d) => `| ${d.id} | ${d.severity} | ${d.triageStatus} | ${d.title.replace(/\|/g, '/')} |`,
      ),
      '',
    )
  }

  lines.push('## Pages visited', '', ...pagesVisited.map((url) => `- ${url}`), '')

  if (input.auditTrail && input.auditTrail.length > 0) {
    lines.push(
      '## Audit trail',
      '',
      ...input.auditTrail.map((e) => `- **${e.phase}** / ${e.agent}: \`${e.action}\` — ${e.reason}`),
      '',
    )
  }

  if (sorted.length > 0) {
    lines.push('## Anomalies', '')
    for (const anomaly of sorted) {
      lines.push(
        `### ${SEVERITY_EMOJI[anomaly.severity]} [${anomaly.severity.toUpperCase()}] ${anomaly.description}`,
        '',
        `- **ID:** ${anomaly.id}`,
        `- **Type:** ${anomaly.type}`,
        `- **Page:** ${anomaly.pageUrl}`,
        `- **Detected at:** ${anomaly.timestamp}`,
        `- **Action trail:** ${anomaly.actionTrail.length > 0 ? anomaly.actionTrail.join(' → ') : '(page load)'}`,
        anomaly.screenshotPath ? `- **Screenshot:** ${path.basename(path.dirname(anomaly.screenshotPath))}/${path.basename(anomaly.screenshotPath)}` : '',
        '',
        '```',
        anomaly.evidence,
        '```',
        '',
      )
    }
  }

  lines.push(
    '---',
    '_Generated by the explore:bugs mini-orchestrator (setup → crawl → triage → review → reporting → rag). ' +
      'Anomalies are heuristic signals, not confirmed defects — triage them like any other bug report._',
  )

  return lines.filter((line, index, arr) => !(line === '' && arr[index - 1] === '')).join('\n')
}
