import * as path from 'node:path'
import { Anomaly } from './types'

const SEVERITY_ORDER: Record<Anomaly['severity'], number> = { critical: 0, major: 1, minor: 2 }
const SEVERITY_EMOJI: Record<Anomaly['severity'], string> = { critical: '🔴', major: '🟠', minor: '⚪' }

export function buildMarkdownReport(input: {
  runId: string
  startUrl: string
  pagesVisited: string[]
  actionsPerformed: number
  anomalies: Anomaly[]
}): string {
  const { runId, startUrl, pagesVisited, actionsPerformed, anomalies } = input
  const critical = anomalies.filter((a) => a.severity === 'critical')
  const major = anomalies.filter((a) => a.severity === 'major')
  const minor = anomalies.filter((a) => a.severity === 'minor')

  const sorted = [...anomalies].sort((a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity])

  const lines: string[] = [
    `# Exploration report — ${runId}`,
    '',
    `**Start URL:** ${startUrl}`,
    `**Pages visited:** ${pagesVisited.length}`,
    `**Actions performed:** ${actionsPerformed}`,
    `**Anomalies found:** ${anomalies.length} (${critical.length} critical, ${major.length} major, ${minor.length} minor)`,
    '',
    '## Summary',
    '',
    anomalies.length === 0
      ? 'No anomalies detected during this exploration run. 🎉'
      : `| Severity | Count |\n| --- | --- |\n| 🔴 Critical | ${critical.length} |\n| 🟠 Major | ${major.length} |\n| ⚪ Minor | ${minor.length} |`,
    '',
    '## Pages visited',
    '',
    ...pagesVisited.map((url) => `- ${url}`),
    '',
  ]

  if (sorted.length > 0) {
    lines.push('## Anomalies', '')
    for (const anomaly of sorted) {
      lines.push(
        `### ${SEVERITY_EMOJI[anomaly.severity]} [${anomaly.severity.toUpperCase()}] ${anomaly.description}`,
        '',
        `- **ID:** ${anomaly.id}`,
        `- **Type:** ${anomaly.type}`,
        `- **Page:** ${anomaly.pageUrl}`,
        `- **Detected at:** ${anomaly.timestamp}`,
        `- **Action trail:** ${anomaly.actionTrail.length > 0 ? anomaly.actionTrail.join(' → ') : '(page load)'}`,
        anomaly.screenshotPath ? `- **Screenshot:** ${path.basename(path.dirname(anomaly.screenshotPath))}/${path.basename(anomaly.screenshotPath)}` : '',
        '',
        '```',
        anomaly.evidence,
        '```',
        '',
      )
    }
  }

  lines.push(
    '---',
    '_This report was generated by the autonomous bug-hunter exploration agent. It performs exploratory QA — ' +
      'clicking through controls and watching for JS errors, failed network calls, and visible error text — ' +
      'without needing pre-written test cases. Anomalies are heuristic signals, not confirmed defects; triage ' +
      'them like any other bug report._',
  )

  return lines.filter((line, index, arr) => !(line === '' && arr[index - 1] === '')).join('\n')
}
